# Load and explore the data

## Import libraries

In [1]:
# Import pandas, numpy, and matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# seaborn is a data visualization library built on matplotlib
import seaborn as sns

# set the plotting style
sns.set_style("whitegrid")

## Load the data

In [2]:
df_seattle = pd.read_csv("/Users/anhtuyet15999/Projects/weather/data/raw/seattle_rain.csv")

In [5]:
df_boston = pd.read_csv("/Users/anhtuyet15999/Projects/weather/data/raw/boston_rain.csv")

## Explore the contents of the data sets

In [3]:
df_seattle.head()

,STATION,NAME,DATE,DAPR,MDPR,PRCP,SNOW,SNWD,WESD,WESF
0,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/1/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
1,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/2/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
2,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/3/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
3,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/4/18,NaN,NaN,0.00,NaN,NaN,NaN,NaN
4,US1WAKG0225,"SEATTLE 2.1 ESE, WA US",1/5/18,NaN,NaN,0.25,NaN,NaN,NaN,NaN

In [4]:
df_seattle.info()

<class 'pandas.DataFrame'>
RangeIndex: 1658 entries, 0 to 1657
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  1658 non-null   str
 1   NAME     1658 non-null   str
 2   DATE     1658 non-null   str
 3   DAPR     23 non-null     float64
 4   MDPR     23 non-null     float64
 5   PRCP     1636 non-null   float64
 6   SNOW     353 non-null    float64
 7   SNWD     66 non-null     float64
 8   WESD     15 non-null     float64
 9   WESF     28 non-null     float64
dtypes: float64(7), str(3)
memory usage: 194.4 KB

In [6]:
df_boston.head()

       STATION                      NAME        DATE  PRCP  SNOW  SNWD
0  USC00198368  NWS BOSTON NORTON, MA US  2018-01-01  0.00   0.0   0.0
1  USC00198368  NWS BOSTON NORTON, MA US  2018-01-02  0.00   0.0   0.0
2  USC00198368  NWS BOSTON NORTON, MA US  2018-01-03  0.00   0.0   0.0
3  USC00198368  NWS BOSTON NORTON, MA US  2018-01-04  0.00   0.0   0.0
4  USC00198368  NWS BOSTON NORTON, MA US  2018-01-05  1.65  16.9  15.0

In [7]:
df_boston.info()

<class 'pandas.DataFrame'>
RangeIndex: 1826 entries, 0 to 1825
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  1826 non-null   str
 1   NAME     1826 non-null   str
 2   DATE     1826 non-null   str
 3   PRCP     1826 non-null   float64
 4   SNOW     1826 non-null   float64
 5   SNWD     1824 non-null   float64
dtypes: float64(3), str(3)
memory usage: 166.0 KB

### check station, date, convert date to datetime, 
#

## Why might the St. Louis data set be larger?

#### Examine the `STATION` column